-- Generated by nwg-displays on 2026-09-30 at 17:52:37. Do not edit manually.

hl.monitor({
    output = "Virtual-1",
    mode = "1920x1200@59.88",
    position = "0x0",
    scale = 1,
    vrr = 0
})
