# Paleta de kitty de Albert: base del fondo + colores ANSI armonizados (matugen)

cursor #f5bc6f
cursor_text_color #452b00

foreground            #ede0d4
background            #18120b
selection_foreground  #ffddb4
selection_background  #633f00
url_color             #f5bc6f

# negro
color0   #3b342b
color8   #9c8f80

# rojo
color1   #ffb4a4
color9   #ffdad3

# verde
color2   #bece7f
color10  #daea98

# amarillo
color3   #f1be6d
color11  #ffdeae

# azul (el prompt lo usa para la ruta: va en el color principal)
color4   #f5bc6f
color12  #8dcff2

# magenta
color5   #f4b2e3
color13  #ffd7f2

# cian
color6   #80d5cf
color14  #9df1eb

# blanco
color7   #d3c4b4
color15  #ede0d4

# Pestañas y bordes
active_tab_foreground     #452b00
active_tab_background     #f5bc6f
active_tab_font_style     bold
inactive_tab_foreground   #d3c4b4
inactive_tab_background   #302921
tab_bar_background        #18120b
active_border_color       #f5bc6f
inactive_border_color     #4f4539
